version: "3.8"

services:

  configserver:
    image: aniramki/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - bankapplication

  eurekaserver:
    image: aniramki/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - bankapplication
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: aniramki/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bankapplication
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurecaserver:8070/eureka/

  loans:
    image: aniramki/accounts:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bankapplication
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurecaserver:8070/eureka/

  cards:
    image: aniramki/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bankapplication
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurecaserver:8070/eureka/


